
###
// Admin returns full details
###
GET http://localhost:3001/api/addressOrder
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOjEsImlhdCI6MTcwMDEwNzIwOH0.snNtCB_yW-bmPjwdBpLVtoWTCx6V75ifkbW85gP2gL8


###
//                                NEW addressOrder
###
###
// No Auth should fail
###
Post http://localhost:3001/api/addressOrder
Content-Type: application/json

{
    "addressId": 6,
    "orderId": 1
}
###
// NotAdmin should Pass
###
Post http://localhost:3001/api/addressOrder
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5vdEFkbWluIiwiaWQiOjIsImlhdCI6MTcwMDgwNDMyOX0.pT2yrxcMrz_9s04q-DS2vFmVkJMNTIMaMg9X6DdVWvA

{
    "addressId": 2,
    "orderId": 7
}
###
// Admin Should pass
###
Post http://localhost:3001/api/addressOrder
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOjEsImlhdCI6MTcwMDEwOTY1Nn0.qGxTUcyswhnYXxpV5plp7vhf4Ic2dctHO8ntG6F88jY

{
    "addressId": 1,
    "orderId": 2
}
###






###
//                             Deleting addressOrder
###
###
//No Auth should fail
###
DELETE  http://localhost:3001/api/addressOrder
Content-Type: application/json

{
    "addressId": 6,
    "orderId": 1
}
###
//Random User should Fail
###
DELETE  http://localhost:3001/api/addressOrder
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5vdEFkbWluIiwiaWQiOjIsImlhdCI6MTcwMDM1NDQxMX0.a7zAsEhH0PvozVCnezJUuAlLfqS26u5kx90TGocVolM

{
    "addressId": 6,
    "orderId": 1
}
###
//Admin should delete
###
DELETE  http://localhost:3001/api/addressOrder
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOjEsImlhdCI6MTcwMDA4MzI3M30.yl_Lf_zEJklIHXBHKq5BuL14Nbg4MI5NjBJFJjK3mgE

{
    "addressId": 1,
    "orderId": 1
}




