GET http://localhost:3001/api/notes
###
GET http://localhost:3001/api/users
###
GET http://localhost:3001/api/notes/1
###
Post http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "This is a Test",
  "date": "11-11-1111",
  "important": false
}
###
Post http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "Admin",
    "name": "Test",
    "password": "secret"
}
###
Post http://localhost:3001/api/login
Content-Type: application/json
 
{
    "username": "Admin",
    "password": "secret"
}
###
DELETE  http://localhost:3003/api/blogs/6507d419ed3ac3259a16b543
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJ1YmFuIiwiaWQiOjEsImlhdCI6MTY5OTMyNjk3MX0.VtZ_8-QzSW1x32vUlloVyBGZ3_io3_O-dO6IrfBHBvw
###
Post http://localhost:3001/api/notes
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJ1YmFuIiwiaWQiOjEsImlhdCI6MTY5OTMzMzc3Nn0.wM7rDJgP9G6GDk7hBEZXfuMowmC2odc0R9hVRLrCIS8

{
  "content": "This is a Test2",
  "date": "22-22-2222",
  "important": false
}


