###
//                            GET all Categories
###
// No Auth returns min
###
GET http://localhost:3001/api/category
###
// NotAdmin returns min
###
GET http://localhost:3001/api/category
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5vdEFkbWluIiwiaWQiOjIsImlhdCI6MTcwMDA5OTAxM30.GK8CBJgRwmMQE4SdUY6VUsyR9OcC4g1L49Zck8YB7Yg

###
// Admin returns full details
###
GET http://localhost:3001/api/category
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOjEsImlhdCI6MTcwMDA5ODk2Mn0.tVvXFdacViNlwVtXDOKOycKFPcO_wdjmt15IA2MpJDw






###
###
//                            Change Category
###
// Fail with no Auth
###
PUT http://localhost:3001/api/category/1
Content-Type: application/json

{
    "categoryName": "Test Item C",
    "categoryDescription": "Test Desc C"
}
###
// Admin Pass
###
PUT http://localhost:3001/api/category/1
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOjEsImlhdCI6MTcwMDA5ODk2Mn0.tVvXFdacViNlwVtXDOKOycKFPcO_wdjmt15IA2MpJDw

{
    "categoryName": "Test Item B",
    "categoryDescription": "Test Desc B"
}
###
// NotAdmin should fail
###
PUT http://localhost:3001/api/category/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5vdEFkbWluIiwiaWQiOjIsImlhdCI6MTcwMDA5OTAxM30.GK8CBJgRwmMQE4SdUY6VUsyR9OcC4g1L49Zck8YB7Yg

{
    "categoryName": "Test Item C",
    "categoryDescription": "Test Desc C"
}


###
//                                NEW Category
###
###
// No Auth should fail
###
Post http://localhost:3001/api/category/1
Content-Type: application/json

{
    "categoryName": "Test Item C",
    "categoryDescription": "Test Desc C"
}
###
// NotAdmin should fail
###
Post http://localhost:3001/api/category
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5vdEFkbWluIiwiaWQiOjIsImlhdCI6MTcwMDA5OTAxM30.GK8CBJgRwmMQE4SdUY6VUsyR9OcC4g1L49Zck8YB7Yg

{
    "categoryName": "Test Item C",
    "categoryDescription": "Test Desc C"
}
###
// Admin Should pass
###
Post http://localhost:3001/api/category
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOjEsImlhdCI6MTcwMDA5ODk2Mn0.tVvXFdacViNlwVtXDOKOycKFPcO_wdjmt15IA2MpJDw

{
    "categoryName": "Test Item E",
    "categoryDescription": "Test Desc C"
}
###


###
//                             Deleting Item
###
###
//No Auth should fail
###
DELETE  http://localhost:3001/api/category/3
Content-Type: application/json
###
//Random User should Fail
###
DELETE  http://localhost:3001/api/category/3
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5vdEFkbWluIiwiaWQiOjIsImlhdCI6MTcwMDA5OTAxM30.GK8CBJgRwmMQE4SdUY6VUsyR9OcC4g1L49Zck8YB7Yg
###
//Admin should delete
###
DELETE  http://localhost:3001/api/category/3
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOjEsImlhdCI6MTcwMDA5ODk2Mn0.tVvXFdacViNlwVtXDOKOycKFPcO_wdjmt15IA2MpJDw






