###
//                            GET all Orders
###
// No Auth returns min
###
GET http://localhost:3001/api/orders
###
// NotAdmin returns min
###
GET http://localhost:3001/api/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5vdEFkbWluIiwiaWQiOjIsImlhdCI6MTcwMDgwNDMyOX0.pT2yrxcMrz_9s04q-DS2vFmVkJMNTIMaMg9X6DdVWvA

###
// Admin returns full details
###
GET http://localhost:3001/api/orders
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOjEsImlhdCI6MTcwMDEwOTY1Nn0.qGxTUcyswhnYXxpV5plp7vhf4Ic2dctHO8ntG6F88jY




###
###
//                            Change Items
###
// Fail with no Auth
###
PUT http://localhost:3001/api/orders/1
Content-Type: application/json

{
    "status": "Test Item A"
}
###
// Admin Pass
###
PUT http://localhost:3001/api/orders/1
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOjEsImlhdCI6MTcwMDA5ODk2Mn0.tVvXFdacViNlwVtXDOKOycKFPcO_wdjmt15IA2MpJDw

{
    "status": "Test Item A"
}
###
// NotAdmin should fail
###
PUT http://localhost:3001/api/orders/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5vdEFkbWluIiwiaWQiOjIsImlhdCI6MTcwMDA5OTAxM30.GK8CBJgRwmMQE4SdUY6VUsyR9OcC4g1L49Zck8YB7Yg

{
    "status": "Test Item A"
}


###
//                                NEW Order
###
###
// No Auth should fail
###
Post http://localhost:3001/api/orders
Content-Type: application/json

{
    "status": "Not Prepared",
    "totalSale": 9999,
    "totalCost": 1111
}
###
// NotAdmin should Pass
###
Post http://localhost:3001/api/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5vdEFkbWluIiwiaWQiOjIsImlhdCI6MTcwMDA5OTAxM30.GK8CBJgRwmMQE4SdUY6VUsyR9OcC4g1L49Zck8YB7Yg


{
    "status": "Not Prepared",
    "totalSale": 9999,
    "totalCost": 1111
}

###
// Admin Should pass
###
Post http://localhost:3001/api/orders
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOjEsImlhdCI6MTcwMDEwOTY1Nn0.qGxTUcyswhnYXxpV5plp7vhf4Ic2dctHO8ntG6F88jY

{

    "status": "Not Prepared",
    "totalSale": 9999,
    "totalCost": 1111

}
###
###
// Test with no Address SHould Fail
###
Post http://localhost:3001/api/orders
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QiLCJpZCI6MywiaWF0IjoxNzAwMTY5MDMwfQ.YE5iz9AysUEhDsVTFbTpig7dT50vqlpJ89nKR8BB2hI

{

    "status": "Not Prepared",
    "totalSale": 9999,
    "totalCost": 1111

}
###



###
//                             Deleting Item
###
###
//No Auth should fail
###
DELETE  http://localhost:3001/api/orders/1
Content-Type: application/json
###
//Random User should Fail
###
DELETE  http://localhost:3001/api/orders/2
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5vdEFkbWluIiwiaWQiOjIsImlhdCI6MTcwMDEwOTY2NH0.MYRnWwqvg5_1ALxnOmOxZnFDCwLBxR8GZvMl1HgPwn4
###
//Admin should delete
###
DELETE  http://localhost:3001/api/orders/1
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOjEsImlhdCI6MTcwMDA5ODk2Mn0.tVvXFdacViNlwVtXDOKOycKFPcO_wdjmt15IA2MpJDw






