###
//                            GET all users
###
GET http://localhost:3001/api/users

###
###
//                            Change Admin and email/phone/pass
###
// Fail with no Auth
###
PUT http://localhost:3001/api/users/test
Content-Type: application/json

{
  "admin": true
}
###
// Admin Pass
###
PUT http://localhost:3001/api/users/test
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOjEsImlhdCI6MTcwMDA4MzI3M30.yl_Lf_zEJklIHXBHKq5BuL14Nbg4MI5NjBJFJjK3mgE

{
  "admin": false
}
###
// NotAdmin
###
PUT http://localhost:3001/api/users/test
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5vdEFkbWluIiwiaWQiOjIsImlhdCI6MTcwMDA4MzQzMX0.Fb-jbqQN17lbknKxwn77xm7UJ49L5Iei3PcbfsMfAbQ

{
  "admin": true,
  "email": "test@testa.com",
  "phone" :"15646874651",
  "password": "secret"
}
###
// Test
###
PUT http://localhost:3001/api/users/test
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QiLCJpZCI6MywiaWF0IjoxNzAwMDgzNTU4fQ.6W45tVGCtFTrFmRbYIg_TaF0h7wAliZ04diy0K8vnU4

{
  "admin": true,
  "email": "test@testa.com",
  "phone" :"15646874651",
  "password": "secret"
}



###
//                                NEW Users
###
###
Post http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "Admin",
    "name": "Test",
    "password": "secret"
}
###



###
//                            Logging In for Tokens
###
Post http://localhost:3001/api/login
Content-Type: application/json
 
{
    "username": "Admin",
    "password": "secret"
}
###
Post http://localhost:3001/api/login
Content-Type: application/json
 
{
    "username": "NotAdmin",
    "password": "secret"
}
###
Post http://localhost:3001/api/login
Content-Type: application/json
 
{
    "username": "Test",
    "password": "secret"
}


###
//                             Deleting Users
###
###
//Same User
###
DELETE  http://localhost:3001/api/users/test
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QiLCJpZCI6OCwiaWF0IjoxNjk5OTM1MjE0fQ.0UNIenGoFkqXrEpOKXM9JrKmkocUMi3qhb6a4cPiLOs
###
//Random User
###
DELETE  http://localhost:3001/api/users/test
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QiLCJpZCI6MywiaWF0IjoxNzAwMDgzNTU4fQ.6W45tVGCtFTrFmRbYIg_TaF0h7wAliZ04diy0K8vnU4
###
//Admin
###
DELETE  http://localhost:3001/api/users/test
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwiaWQiOjEsImlhdCI6MTcwMDA4MzI3M30.yl_Lf_zEJklIHXBHKq5BuL14Nbg4MI5NjBJFJjK3mgE






